"""No direct Store mutation outside Dispatcher.

Covers ``docs/dev/STORE.md`` invariant 1-2:

    Action ──► Dispatcher.dispatch ──► RootReducer.reduce (replace) ──► Store ──► emit_state_change

Any direct assignment to tab-owned session/document state must go through
``store.get_dispatcher().dispatch(Action, scope=...)`` and a reducer that
uses ``dataclasses.replace``. Direct ``store.viewport.session_data.image_state.image1 =``
or ``render_cache.unification_in_progress =`` etc bypasses lock/history/subscribers/
session re-pointing and causes races like preview vanishing / left-on-right.

This AST dogma scans ``src/`` for assignments whose LHS chain contains
``session_data / image_state / render_cache / document`` and fails if found
outside the reducer/store implementation or a transient ``Store()`` builder.

Transient builders (``Store()`` → ``store.get_session_state_slot("document")`` etc)
are exempted via data-flow tracking of ``Store()``-derived variables.
"""

from __future__ import annotations

import ast
from pathlib import Path

from ._framework import SRC, iter_py, read, rel

# Intermediate attributes that denote Store-owned state — generated from real
# Store/ViewportState/SessionData shape + Store top-level fields, not hard-coded
# to one tab. Mirrors test_no_tab_to_tab_service.py: dynamic discovery.
def _build_intermediate() -> set[str]:
    """Collect Store-owned attribute names from live code, not a literal list."""
    inter: set[str] = set()
    # ViewportState slots → render_config, session_data, view_state, interaction_state, geometry_state
    try:
        from core.store_viewport import ViewportState, SessionData

        for cls in (ViewportState, SessionData):
            for s in getattr(cls, "__slots__", ()):
                inter.add(s.lstrip("_"))
    except Exception:
        inter.update({"render_config", "session_data", "view_state", "interaction_state", "geometry_state"})
    # SessionData opaque children — always tab-owned
    inter.update({"image_state", "render_cache"})
    # Store top-level discriminants — keep only Store-unique names to avoid
    # false positives on generic `self.workspace` / `self.settings` (MainController etc.)
    # `viewport`/`document`/`state_slots` are Store-unique, `settings`/`workspace`/`runtime_cache`
    # are generic and would flag unrelated `self.workspace = WorkspaceSessionActions(...)` etc.
    inter.update({"viewport", "document", "state_slots"})
    # `state_slots` covers `state_slots["multi_compare.state"] = ...` Subscript path
    return inter


INTERMEDIATE: set[str] = _build_intermediate()

# Files that *implement* Store/Reducer machinery — generated by discovery, not hard-coded.
def _build_exempt() -> frozenset[str]:
    """Discover Store/Reducer impl files via filesystem + tab registry."""
    exempt: set[str] = set()
    # Core Store / Viewport / Workspace / Settings impl
    for rel in [
        "src/core/store.py",
        "src/core/store_viewport.py",
        "src/core/store_workspace.py",
        "src/core/store_settings.py",
        "src/core/store_operations.py",
        "src/core/store_runtime_cache.py",
        "src/domain/workspace.py",
        "src/core/state_management/reducers.py",
        "src/core/state_management/extension_reducers.py",
        "src/core/state_management/slot_reducers.py",
        "src/core/state_management/dispatcher.py",
        "src/core/state_management/action_base.py",
    ]:
        exempt.add(rel)
    # Tab-owned state reducers/models — discover via tabs registry (like test_no_tab_to_tab_service.py)
    try:
        tabs_root = SRC / "tabs"
        if tabs_root.is_dir():
            for d in tabs_root.iterdir():
                if d.is_dir() and (d / "tab.py").exists():
                    for suffix in ("state/reducers.py", "state/reducer.py", "state/models.py"):
                        p = d / suffix
                        if p.exists():
                            exempt.add(p.relative_to(SRC.parent).as_posix())
                    # any reducer-named file under the tab
                    for p in d.rglob("*reducer*.py"):
                        if "__pycache__" not in p.parts and "tests" not in p.parts:
                            exempt.add(p.relative_to(SRC.parent).as_posix())
    except Exception:
        pass
    return frozenset(exempt)


EXEMPT: frozenset[str] = _build_exempt()


def _get_chain(node: ast.AST) -> list[str] | None:
    """Return dotted chain for ``a.b.c`` as ``[a, b, c]`` or None."""
    chain: list[str] = []
    cur: ast.AST = node
    while isinstance(cur, ast.Attribute):
        chain.append(cur.attr)
        cur = cur.value  # type: ignore[assignment]
    if isinstance(cur, ast.Name):
        chain.append(cur.id)
        return chain[::-1]
    if isinstance(cur, ast.Attribute):
        sub = _get_chain(cur)
        if sub is not None:
            return sub + chain[::-1]
    return None


def _collect_transients(tree: ast.Module) -> set[str]:
    """Variables directly or transitively derived from ``Store()`` construction."""
    transients: set[str] = set()
    # direct Store()/SessionData() constructors
    for node in ast.walk(tree):
        if isinstance(node, ast.Assign) and len(node.targets) == 1 and isinstance(node.targets[0], ast.Name):
            name = node.targets[0].id
            val = node.value
            if isinstance(val, ast.Call):
                func = val.func
                func_name = ""
                if isinstance(func, ast.Name):
                    func_name = func.id
                elif isinstance(func, ast.Attribute):
                    func_name = func.attr
                if func_name in {
                    "Store",
                    "SessionData",
                    "ImageSessionState",
                    "RenderCacheState",
                    "ViewportState",
                    "DocumentModel",
                }:
                    transients.add(name)
    # transitively derived: x = <expr containing transient var>
    changed = True
    while changed:
        changed = False
        for node in ast.walk(tree):
            if isinstance(node, ast.Assign) and len(node.targets) == 1 and isinstance(node.targets[0], ast.Name):
                lhs = node.targets[0].id
                if lhs in transients:
                    continue
                rhs = node.value
                for sub in ast.walk(rhs):
                    if isinstance(sub, ast.Name) and sub.id in transients:
                        transients.add(lhs)
                        changed = True
                        break
                    if isinstance(sub, ast.Attribute):
                        chain = _get_chain(sub)
                        if chain and chain[0] in transients:
                            transients.add(lhs)
                            changed = True
                            break
                if changed:
                    break
    return transients


def _direct_store_mutations() -> list[tuple[str, int, str]]:
    offenders: list[tuple[str, int, str]] = []
    for path in iter_py(SRC):
        rel_path = rel(path)
        if rel_path in EXEMPT:
            continue
        try:
            tree = ast.parse(read(path))
        except SyntaxError:
            continue
        transients = _collect_transients(tree)
        for node in ast.walk(tree):
            targets: list[ast.AST] = []
            if isinstance(node, ast.Assign):
                targets = node.targets
            elif isinstance(node, ast.AnnAssign) and node.target is not None:
                targets = [node.target]
            elif isinstance(node, ast.AugAssign):
                targets = [node.target]
            else:
                continue
            for target in targets:
                elts: list[ast.AST] = []
                if isinstance(target, ast.Attribute):
                    elts = [target]
                elif isinstance(target, ast.Tuple):
                    elts = target.elts
                elif isinstance(target, ast.Subscript):
                    elts = [target]
                else:
                    continue
                for elt in elts:
                    chain: list[str] | None = None
                    display = ""
                    if isinstance(elt, ast.Attribute):
                        chain = _get_chain(elt)
                        if chain is None:
                            continue
                        display = ".".join(chain)
                    elif isinstance(elt, ast.Subscript):
                        # state_slots["document"] = ...  or  state_slots["multi_compare.state"] = ...
                        val = elt.value
                        if isinstance(val, ast.Attribute):
                            chain = _get_chain(val)
                        elif isinstance(val, ast.Name):
                            chain = [val.id]
                        else:
                            continue
                        if chain is None:
                            continue
                        # display with subscript for report
                        try:
                            sub_text = ast.unparse(elt).strip()  # type: ignore
                        except Exception:
                            sub_text = ".".join(chain) + "[...]"
                        display = sub_text
                    else:
                        continue
                    if chain is None or not any(part in INTERMEDIATE for part in chain):
                        continue
                    if chain[0] in transients:
                        continue
                    offenders.append((rel_path, node.lineno, display))
    return sorted(offenders)


def test_no_direct_store_mutation():
    offenders = _direct_store_mutations()
    assert not offenders, (
        "Direct Store mutation outside Dispatcher/Reducer — "
        "use store.get_dispatcher().dispatch(Action, scope=...) → replace() instead "
        f"({len(offenders)} hits):\n  " + "\n  ".join(f"{p}:{ln} — {chain} = ..." for p, ln, chain in offenders)
    )
