"""Magnifier feature constants — owned by the magnifier canvas feature."""
from domain.types import Point

DEFAULT_MAGNIFIER_SIZE_RELATIVE = 0.4
DEFAULT_CAPTURE_SIZE_RELATIVE = 0.1
DEFAULT_CAPTURE_POS_RELATIVE = Point(0.5, 0.5)
DEFAULT_MAGNIFIER_OFFSET_RELATIVE = Point(0.0, -0.15)
DEFAULT_MAGNIFIER_SPACING_RELATIVE = 0.02

MIN_MAGNIFIER_SPACING_RELATIVE = 0.0
MAX_MAGNIFIER_SPACING_RELATIVE = 0.05
MIN_MAGNIFIER_SPACING_RELATIVE_FOR_COMBINE = 0.005

CAPTURE_THICKNESS_FACTOR = 0.35
MIN_CAPTURE_THICKNESS = 1
MAX_CAPTURE_THICKNESS = 4
MIN_MAG_BORDER_THICKNESS = 1
MAX_MAG_BORDER_THICKNESS = 4
