from .cache import reduce_magnifier_cache_state
from .geometry import reduce_magnifier_geometry_state
from .interaction import reduce_magnifier_interaction_state
from .render_config import reduce_magnifier_render_config
from .view import reduce_magnifier_view_state
