#!/usr/bin/env python3
"""Validate cross-doc markdown links and generate a backlink index.

Scope: every ``*.md`` under ``docs/`` and ``src/tabs/<tab>/docs/`` (host docs
+ tab-owned docs). This is the "dynamic linking" layer for
``docs/dev/DOC_INDEX.md`` — instead of hand-maintained "See also" / index
bullet lists that silently rot when a file moves, this script:

1. Parses every relative markdown link (``[text](path#anchor)``) in every
   doc, resolves it against the linking file's directory, and reports any
   that don't point at a real file/dir on disk (a moved/renamed doc breaks
   this immediately instead of quietly).
2. Regenerates ``docs/dev/DOC_INDEX.md``: every doc in scope, grouped by
   directory, each with a "Referenced by" backlink list computed from the
   link graph — so nobody hand-maintains which docs point at which.

Usage:
    python src/devtools/docs_link_graph.py            # report
    python src/devtools/docs_link_graph.py --json
    python src/devtools/docs_link_graph.py --strict    # exit 1 on broken links
    python src/devtools/docs_link_graph.py --write-index   # regenerate DOC_INDEX.md
"""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

_LINK_RE = re.compile(r"\[([^\]]*)\]\(([^)]+)\)")
_INDEX_REL_PATH = "docs/dev/DOC_INDEX.md"
_GENERATED_MARKER = "<!-- AUTO-GENERATED by src/devtools/docs_link_graph.py — do not hand-edit -->"


@dataclass(frozen=True, slots=True)
class BrokenLink:
    source: str  # repo-relative path of the file containing the link
    line: int
    text: str
    target: str  # raw link target as written


@dataclass(frozen=True, slots=True)
class DocsLinkReport:
    docs: tuple[str, ...]  # repo-relative paths, sorted
    broken: tuple[BrokenLink, ...]
    backlinks: dict[str, tuple[str, ...]]  # doc -> sorted docs that link to it


def default_repo_root() -> Path:
    return Path(__file__).resolve().parents[2]


def discover_doc_files(repo_root: Path) -> list[Path]:
    """Every ``*.md`` under ``docs/`` and each tab's ``docs/`` package."""
    out: list[Path] = []
    docs_root = repo_root / "docs"
    if docs_root.is_dir():
        out.extend(sorted(docs_root.rglob("*.md")))
    tabs_root = repo_root / "src" / "tabs"
    if tabs_root.is_dir():
        for tab_docs in sorted(tabs_root.glob("*/docs")):
            if tab_docs.is_dir():
                out.extend(sorted(tab_docs.rglob("*.md")))
    return [p for p in out if "__pycache__" not in p.parts]


def _rel(path: Path, *, repo_root: Path) -> str:
    try:
        return path.relative_to(repo_root).as_posix()
    except ValueError:
        return path.as_posix()


def _is_external(target: str) -> bool:
    return bool(re.match(r"^[a-zA-Z][a-zA-Z0-9+.-]*:", target)) or target.startswith("//")


def _resolve_link(target: str, *, doc_path: Path, repo_root: Path) -> Path | None:
    """Resolve a relative link target to an absolute path, stripping any anchor.

    Returns None for links this checker doesn't validate (external URLs,
    pure same-file anchors, mailto:, etc).
    """
    target = target.strip()
    if not target or _is_external(target) or target.startswith("mailto:"):
        return None
    if target.startswith("#"):
        return None  # same-file anchor
    path_part = target.split("#", 1)[0]
    if not path_part:
        return None
    if path_part.startswith("/"):
        resolved = repo_root / path_part.lstrip("/")
    else:
        resolved = (doc_path.parent / path_part).resolve()
    return resolved


def analyze_docs(*, repo_root: Path | None = None) -> DocsLinkReport:
    root = repo_root if repo_root is not None else default_repo_root()
    doc_paths = discover_doc_files(root)
    doc_rels = {_rel(p, repo_root=root) for p in doc_paths}

    broken: list[BrokenLink] = []
    backlinks: dict[str, set[str]] = {rel: set() for rel in doc_rels}

    for doc_path in doc_paths:
        source_rel = _rel(doc_path, repo_root=root)
        text = doc_path.read_text(encoding="utf-8")
        in_fence = False
        for lineno, line in enumerate(text.splitlines(), start=1):
            if line.lstrip().startswith("```"):
                in_fence = not in_fence
                continue
            if in_fence:
                continue
            for match in _LINK_RE.finditer(line):
                link_text, target = match.group(1), match.group(2)
                resolved = _resolve_link(target, doc_path=doc_path, repo_root=root)
                if resolved is None:
                    continue
                if not resolved.exists():
                    broken.append(
                        BrokenLink(source=source_rel, line=lineno, text=link_text, target=target)
                    )
                    continue
                target_rel = _rel(resolved, repo_root=root)
                if target_rel in doc_rels and target_rel != source_rel:
                    backlinks[target_rel].add(source_rel)

    return DocsLinkReport(
        docs=tuple(sorted(doc_rels)),
        broken=tuple(broken),
        backlinks={k: tuple(sorted(v)) for k, v in backlinks.items()},
    )


def _doc_title(doc_rel: str, *, repo_root: Path) -> str:
    path = repo_root / doc_rel
    try:
        for line in path.read_text(encoding="utf-8").splitlines():
            stripped = line.strip()
            if stripped.startswith("# "):
                return stripped[2:].strip()
    except OSError:
        pass
    return Path(doc_rel).stem


def render_index(report: DocsLinkReport, *, repo_root: Path | None = None) -> str:
    root = repo_root if repo_root is not None else default_repo_root()
    lines: list[str] = [
        "# Doc Index",
        "",
        _GENERATED_MARKER,
        "",
        "Every doc under `docs/` and `src/tabs/<tab>/docs/`, grouped by",
        "directory, with auto-computed backlinks (who links to this doc).",
        "Regenerate: `python src/devtools/docs_link_graph.py --write-index`.",
        "Checked by `tests/devtools/test_docs_link_graph.py`.",
        "",
    ]

    by_dir: dict[str, list[str]] = {}
    for doc_rel in report.docs:
        by_dir.setdefault(str(Path(doc_rel).parent), []).append(doc_rel)

    for directory in sorted(by_dir):
        lines.append(f"## {directory}/")
        lines.append("")
        for doc_rel in sorted(by_dir[directory]):
            title = _doc_title(doc_rel, repo_root=root)
            index_dir = Path(_INDEX_REL_PATH).parent
            rel_from_index = _relpath(doc_rel, from_dir=str(index_dir))
            lines.append(f"- **[{title}]({rel_from_index})** — `{doc_rel}`")
            refs = report.backlinks.get(doc_rel, ())
            if refs:
                ref_links = ", ".join(
                    f"[{r}]({_relpath(r, from_dir=str(index_dir))})" for r in refs
                )
                lines.append(f"  Referenced by: {ref_links}")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def _relpath(target_rel: str, *, from_dir: str) -> str:
    import os

    return os.path.relpath(target_rel, start=from_dir).replace("\\", "/")


def _print_report(report: DocsLinkReport) -> int:
    print(f"Docs scanned: {len(report.docs)}")
    print(f"Broken links: {len(report.broken)}")
    if report.broken:
        print()
        print("Broken links:")
        for b in report.broken:
            print(f"  - {b.source}:{b.line} [{b.text}]({b.target})")
    return len(report.broken)


def main(argv: Iterable[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo-root", type=Path, default=default_repo_root())
    parser.add_argument("--json", action="store_true")
    parser.add_argument("--strict", action="store_true", help="Exit 1 on any broken link.")
    parser.add_argument(
        "--write-index",
        action="store_true",
        help="Regenerate docs/dev/DOC_INDEX.md in place.",
    )
    args = parser.parse_args(list(argv) if argv is not None else None)

    report = analyze_docs(repo_root=args.repo_root)

    if args.write_index:
        content = render_index(report, repo_root=args.repo_root)
        (args.repo_root / _INDEX_REL_PATH).write_text(content, encoding="utf-8")
        print(f"Wrote {_INDEX_REL_PATH}")
        # DOC_INDEX.md itself is part of the scanned corpus, so writing it
        # can change the link/backlink graph — recompute before reporting.
        report = analyze_docs(repo_root=args.repo_root)

    if args.json:
        import json

        payload = {
            "docs": list(report.docs),
            "broken": [
                {"source": b.source, "line": b.line, "text": b.text, "target": b.target}
                for b in report.broken
            ],
        }
        print(json.dumps(payload, ensure_ascii=False, indent=2))
    else:
        _print_report(report)

    if args.strict and report.broken:
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
