from PyQt6.QtCore import QPointF

class AppConstants:
    DISPLAY_RESOLUTION_OPTIONS = {
        "Original": 0,
        "8K (4320p)": 4320,
        "4K (2160p)": 2160,
        "2K (1440p)": 1440,
        "Full HD (1080p)": 1080,
    }
    DEFAULT_DISPLAY_RESOLUTION_LIMIT = 2160

    MIN_NAME_LENGTH_LIMIT = 10
    MAX_NAME_LENGTH_LIMIT = 150
    DEFAULT_MAGNIFIER_SIZE_RELATIVE = 0.4
    DEFAULT_CAPTURE_SIZE_RELATIVE = 0.1
    DEFAULT_CAPTURE_POS_RELATIVE = QPointF(0.5, 0.5)
    DEFAULT_MAGNIFIER_OFFSET_RELATIVE = QPointF(0.0, -0.15)
    DEFAULT_MAGNIFIER_SPACING_RELATIVE = 0.1

    MIN_MAGNIFIER_SPACING_RELATIVE = 0.0
    MAX_MAGNIFIER_SPACING_RELATIVE = 0.5
    MIN_MAGNIFIER_SPACING_RELATIVE_FOR_COMBINE = 0.001

    DEFAULT_JPEG_QUALITY = 93
    DEFAULT_INTERPOLATION_METHOD = "LANCZOS"
    BASE_MOVEMENT_SPEED = 0.5
    CAPTURE_THICKNESS_FACTOR = 0.35

    MIN_CHANGE_THRESHOLD = 0.0001
    SMOOTHING_FACTOR_POS = 0.15
    SMOOTHING_FACTOR_SPACING = 0.2
    SMOOTHING_FACTOR_SPLIT = 0.2
    LERP_STOP_THRESHOLD = 0.001
    MAX_TARGET_DELTA_PER_TICK = 0.1

    MIN_CAPTURE_THICKNESS = 1
    MAX_CAPTURE_THICKNESS = 4
    MIN_MAG_BORDER_THICKNESS = 1
    MAX_MAG_BORDER_THICKNESS = 4
    INTERPOLATION_METHODS_MAP = {
        "NEAREST": "Nearest Neighbor",
        "BILINEAR": "Bilinear",
        "BICUBIC": "Bicubic",
        "LANCZOS": "Lanczos",
        "EWA_LANCZOS": "EWA Lanczos",
    }

    FLYOUT_ANIMATION_DURATION_MS = 150
    TEXT_SETTINGS_FLYOUT_ANIMATION_DURATION_MS = 150

    PROGRESSIVE_LOAD_THRESHOLD_BYTES = 2 * 1024 * 1024
    PROGRESSIVE_LOAD_THRESHOLD_PIXELS = 1920 * 1080

