from __future__ import annotations

from typing import Protocol, runtime_checkable

from domain.types import Point

@runtime_checkable
class OverlayMovementHandler(Protocol):

    def get_offset(self) -> Point | None: ...

    def get_spacing(self) -> float | None: ...

    def get_internal_split(self) -> float | None: ...

    def has_both_sides(self) -> bool: ...

    def set_offset(self, offset: Point) -> None: ...

    def set_spacing(self, spacing: float) -> None: ...

    def get_spacing_limits(self) -> tuple[float, float]: ...

    def emit_combined_state(self, event_bus=None) -> None: ...
